### ISSUE TITLE
No checking of whether image loading failed in draw_x functions

### ISSUE THREAD

**Issue by ahmad-PH** [UTAP/RSDL#1]
if you call a draw_x function from the Window class, and there's some error in the file name (misspelled) or the image fails to load for any reason, this failure will be indicated by neither a return value, nor a thrown exception. you'll just get a window filled with random pixels.

**Comment by hadisfr** [comment]
You mean every one of `draw_bmp`, `draw_png`, and `draw_bg` by _draw_x_? Be clearer.
Actually there won't be any _random pixels_ as you said. If the specified picture could not be loaded in run time, e.g. the file is not available, the programme may break or silently fail based on `SDL_ASSERT_LEVEL`. In the second case, there nothing will happen and the previous state will be hold.
It's possible to check return value of following function call (and similar ones) and check if it is `0` (OK) or `-1` (any error), but I think it's unnecessary and prefer the current behaviour.
https://github.com/UTAP/RSDL/blob/df844dd0e9cfdeb202cc602dbf2127d42aa2d203/src/rsdl.cpp#L187

**Comment by ahmad-PH** [comment]
yes, I do mean the `draw_bmp`, `draw_png`, and `draw_bg` functions.
the problem is there is no way for the programmer to check whether the image loaded successfully, as you said, the program will break or silently fail (leading to things like random pixels being shown).
in similar scenarios in other libraries, the failing of the function will be indicated by either a thrown exception, or a special return value. 
I don't understand why you prefer the current behavior. it's definitely a good thing to be able to explicitly check if opening a file/image was successful instead of just hoping everything went OK.

**Comment by amirs7** [comment]
I prefer that we check these type of errors and throw exceptions. 
Also, we do not have any exception for errors which may happen in other functions like `fill_rect` (check if `x` and `y` are less than `width` and `height`) which I think is necessary.

**Comment by hadisfr** [comment]
@amirs7 Could you add these yourself?

**Comment by hadisfr** [comment]
@ahmad-PH and… Could you please change the examples, too, so that `make` command can work properly?
